#! /usr/bin/env python

'''
	CC0 - Public domain
	http://creativecommons.org/publicdomain/zero/1.0/

	You can use this script like: 
		loggrep my.package.name
	Every additional argument will be passed to `adb logcat`.
	
	You can also pipe some logcat output into this script.

	If you use this in conjunction with some color output scripts, 
	use this first and pipe its output to the color script. Otherwise
	you might get false output.
'''

import os, sys, re

if len(sys.argv) < 2:
	print("You must give at least one argument, that is the package name of your package.")
	sys.exit(1)

if len(sys.argv) > 2:
	adb_args = ' '.join(sys.argv[2:])
else:
	adb_args = ''

# Are we getting input from pipe or do we open the process ourselfs?
if os.isatty(sys.stdin.fileno()):
	input = os.popen("adb %s logcat" % adb_args)
else:
	input = sys.stdin

pkg = sys.argv[1]
lpid = None

# Disable output buffering
unbuffered = os.fdopen(sys.stdout.fileno(), 'w', 0)
sys.stdout = unbuffered

while True:
	try:
		line = input.readline()
	except KeyboardInterrupt:
		break

	# Save process id of process, we are grepping for
	if "Start proc " + pkg in line:
		res = re.search(r'pid=(\d+) ', line)
		lpid = res.group(1)

	if pkg in line:
		print(line.rstrip())
	elif lpid > 0 and str(lpid) + ')' in line:
		print(line.rstrip())
